### ISSUE TITLE
config tweaks

### ISSUE THREAD

**Issue by ghost** [caligin/fooify-ubu#11]
non-mac scrilling
big titlebars on firefox
key to switch language

**Comment by foo-tw** [comment]
dconf write /org/gnome/desktop/peripherals/touchpad/natural-scroll false

**Comment by foo-tw** [comment]
gsettings set org.gnome.settings-daemon.plugins.media-keys screensaver '<Ctrl><Alt>l'

**Comment by caligin** [comment]
titlebars and language switch still to do

**Comment by caligin** [comment]
maybe not a problem anymore
