### ISSUE TITLE
ubuntu20

### ISSUE THREAD

**Issue by caligin** [caligin/fooify-ubu#29]
- review package list
- nautilus setting sort directories first
- terminal alt: cannot use ~ anymore
- theme

**Comment by foo-tw** [comment]
- compose outdated, use `curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)"`
- golang outdated https://golang.org/dl/
- python packages broken, replace with `python3-pip` and `python3`
- something wrong with tor - likely way of installing it changeds
- diffuse does not exist anymore
- mokutils not necessary anymore
- no good reason to have db clients nor ssh server by default
- who uses tree anymore
- awscli has v2 out - check out here https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-linux.html
  - also the -b needs to be `~/bin` and not `~/bin/aws`
- vagrant outdated https://www.vagrantup.com/
